model_type: 2
input_nc: 3
patch_size: 64

#0 - 24GB, 1 - 32GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [256, 32, 10, 8] #amount of images to accumulate before backprop
load_size: [256, 32, 10, 8] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 1
weight_decay: 0.0
dropout_rate: 0.0
augment_key: ["none"]

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 40
max_epochs: 40

dataset_version: "v05_iid"
dataset_repeats: 3

dataset_val_ref: "v05_iid"