model_type: 1
input_nc: 3
patch_size: 64

#0 - 24GB, 1 - 32GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [768, 1024, 320, 256] #amount of images to accumulate before backprop
load_size: [768, 1024, 320, 256] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 10
weight_decay: 0.0
dropout_rate: 0.0
augment_key: ["none"]
use_cbam: False
norm_mode: "batch"

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 200
max_epochs: 200

dataset_version: "v07_iid"
img_to_load: 25000
dataset_repeats: 10